from abc import ABC, abstractmethod
from src.model.alpha_metadata import AlphaMetadata


class MultiAgent(ABC):
    """
    Abstract base class for managing multiple AI agents and their interactions.
    """

    
    @abstractmethod
    def chat(self, user_id: str, message: str) -> AlphaMetadata:
        """
        Process a message through the multi-agent system.
        
        Args:
            user_id: The user ID to process
            message: The input message to process
            
        Returns:
            str: The response generated by the agent system
        """
        pass