server:
  http:
    host: "0.0.0.0"
    nthreads: 4
    port: 5000

default:
  app_name: "ALPHA REPORT CHATBOT"
  env: "LOCAL"
  available_num_processes: 4
  
data_path: 
  history_context_folder: "./data/history_context/"

normal_conversation_agent:
  llm_api_url: "https://saillm.oneops.net/api/chat"
  model: "qwen2.5:14b"
  temperature: 1

function_calling_conversation_agent:
  llm_api_url: "https://saillm.oneops.net/api/chat"
  model: "qwen2.5:14b"
  temperature: 1
  function_list_path: "./data/function_list/function_list.json"
