server:
  http:
    host: "0.0.0.0"
    nthreads: 4
    port: 8000

default:
  app_name: "ALPHA REPORT CHATBOT"
  env: "LOCAL"
  available_num_processes: 4
  

llm:
  api: "https://ollama.selab.edu.vn"
  model: "qwen2.5:14b"

database:
  database_path: "./data/history_context/database.json"


